# Generated by Django 4.2.4 on 2023-08-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eshik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(default='', max_length=201)),
                ('boyi', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='stakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=220)),
                ('hajmi', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
